# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCk87zRiJGDN1E2RDVzOjR6JhopdY0Qd
"""

pip install pandas numpy matplotlib seaborn

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/daily_data.csv')

# Display the first few rows of the dataset
df.head()

df.isnull().sum()

df.dropna(inplace=True)  # Dropping missing values

df['DATE'] = pd.to_datetime(df['DATE'])

df.drop_duplicates(inplace=True)

df.describe()

print(df.columns)

import matplotlib.pyplot as plt

# Convert 'DATE' column to datetime format
df['DATE'] = pd.to_datetime(df['DATE'])

# Plot the Daily Average Dry Bulb Temperature over time
plt.figure(figsize=(12,6))
plt.plot(df['DATE'], df['DailyAverageDryBulbTemperature'], label='Daily Average Temperature')
plt.xlabel('Date')
plt.ylabel('Temperature (°F)')
plt.title('Daily Average Temperature Over Time')
plt.legend()
plt.show()

plt.figure(figsize=(12,6))
plt.plot(df['DATE'], df['DailyMaximumDryBulbTemperature'], label='Daily Maximum Temperature', color='red')
plt.plot(df['DATE'], df['DailyMinimumDryBulbTemperature'], label='Daily Minimum Temperature', color='blue')
plt.xlabel('Date')
plt.ylabel('Temperature (°F)')
plt.title('Daily Maximum and Minimum Temperature Over Time')
plt.legend()
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(df['DATE'], df['DailyAverageDryBulbTemperature'], label='Daily Average Temperature')
plt.xlabel('Date')
plt.ylabel('Temperature (°F)')
plt.title('Daily Average Temperature Over Time')
plt.legend()
plt.show()

# Extract month from date
df['Month'] = df['DATE'].dt.month

# Group by month and calculate the average temperature
monthly_avg_temp = df.groupby('Month')['DailyAverageDryBulbTemperature'].mean()

# Plotting the monthly average temperature
plt.figure(figsize=(10, 6))
monthly_avg_temp.plot(kind='bar', color='skyblue')
plt.xlabel('Month')
plt.ylabel('Average Temperature (°F)')
plt.title('Average Monthly Temperature')
plt.show()

# Extract year from date
df['Year'] = df['DATE'].dt.year

# Group by year and calculate the average temperature
yearly_avg_temp = df.groupby('Year')['DailyAverageDryBulbTemperature'].mean()

# Plotting the yearly average temperature
plt.figure(figsize=(10, 6))
yearly_avg_temp.plot(kind='line', marker='o', color='green')
plt.xlabel('Year')
plt.ylabel('Average Temperature (°F)')
plt.title('Yearly Average Temperature')
plt.show()